Parameters:
  NetworkStack:
    Description: Name of an active Web App Network Stack that contains the networking resource
    Type: String

Resources:
  ServerSecGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow http and ssh on port 80 and 22 respectively and allow all outbound traffic
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
      - IpProtocol: tcp
        FromPort: 0
        ToPort: 65535
        CidrIp: 0.0.0.0/0
      VpcId:
        Fn::ImportValue:
          !Sub "${NetworkStack}-VPCID"

  #Create a launch configuration - It creates a template for Auto Scaling group
  #to launch instance based on scaling rules.launch Config tell how the new instances
  #should be created and their specifications.
  ServerLaunchConfig:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      AssociatePublicIpAddress: true
      ImageId: ami-005bdb005fb00e791
      KeyName: "CFProjectKey"
      InstanceType: t2.medium
      BlockDeviceMappings: 
        - DeviceName: "/dev/sda1"
          Ebs: 
            VolumeSize: "10"
      UserData: 
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
          yum install -y httpd
          systemctl start httpd
          systemctl enable httpd
          wget -P ../../var/www/html https://s3.us-east-2.amazonaws.com/test-udagram-1/index.html
      SecurityGroups:
        - !Ref ServerSecGroup
    DependsOn: ServerSecGroup

  #Create a Target group -
  WebAppTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckIntervalSeconds: 35
      HealthCheckPath: /
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 30
      HealthyThresholdCount: 2
      Port: 80
      Protocol: HTTP
      UnhealthyThresholdCount: 5
      VpcId: 
        Fn::ImportValue:
          !Sub "${NetworkStack}-VPCID"

  #Create a security group for load balancer - 
  ServerSecGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow http and ssh on port 80 and 22 respectively and allow all outbound traffic
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
      - IpProtocol: tcp
        FromPort: 0
        ToPort: 65535
        CidrIp: 0.0.0.0/0
      VpcId:
        Fn::ImportValue:
          !Sub "${NetworkStack}-VPCID"

  WebAppLB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Subnets:
        - Fn::ImportValue:
            !Sub "${NetworkStack}-PUB1"
        - Fn::ImportValue:
            !Sub "${NetworkStack}-PUB2"
      SecurityGroups:
        - !Ref ServerSecGroup

  WebAppLBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    DependsOn:
      - WebAppLB
    Properties:
      DefaultActions:
        - TargetGroupArn: !Ref WebAppTargetGroup
          Type: 'forward'
      LoadBalancerArn: !Ref WebAppLB
      Port: 80
      Protocol: HTTP

  #Finally create an auto scaling group to launch your EC2 instances -
  WebAppAutoScale:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AutoScalingGroupName: !Sub ${NetworkStack}-AutoScale
      AvailabilityZones:
        - !Select [0, !GetAZs '']
        - !Select [1, !GetAZs '']
      VPCZoneIdentifier:
        - Fn::ImportValue:
            !Sub "${NetworkStack}-PUB1" #Change it to private
        - Fn::ImportValue:
            !Sub "${NetworkStack}-PUB2" #Change it to private
      LaunchConfigurationName:
        !Ref ServerLaunchConfig
      TargetGroupARNs:
        - !Ref WebAppTargetGroup
      MinSize: "1"
      MaxSize: "4"
      DesiredCapacity: "4"
      HealthCheckGracePeriod: 180

Outputs:
  LoadBalancer:
    Description: Public URL of Load Balancer
    Value: !Ref WebAppLB
    Export:
      Name: !Sub ${NetworkStack}-LB
