Parameters:
  NetworkStack:
    Description: Name of an active Web App Network Stack that contains the networking resource
    Type: String

  AutoScaleMinSize:
    Description: Minimum number of instances
    Type: String

  AutoScaleMaxSize:
    Description: Maximum number of instances
    Type: String

  AutoScaleDesiredSize:
    Description: Desired number of instances
    Type: String

Resources:
  ServerSecGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow http and ssh on port 80 and allow all outbound traffic
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0
      #- IpProtocol: tcp
      #  FromPort: 22
      #  ToPort: 22
      #  CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
      - IpProtocol: tcp
        FromPort: 0
        ToPort: 65535
        CidrIp: 0.0.0.0/0
      VpcId:
        Fn::ImportValue:
          !Sub "${NetworkStack}-VPCID"

  #Create a launch configuration - It creates a template for Auto Scaling group
  #to launch instance based on scaling rules.launch Config tell how the new instances
  #should be created and their specifications.
  ServerLaunchConfig:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      AssociatePublicIpAddress: true
      ImageId: ami-005bdb005fb00e791
      #KeyName: "CFProjectKey"
      InstanceType: t2.medium
      BlockDeviceMappings: 
        - DeviceName: "/dev/sda1"
          Ebs: 
            VolumeSize: "10"
      UserData: 
        Fn::Base64: !Sub |
          #!/bin/bash
          apt-get update -y
          apt-get install unzip awscli -y
          apt-get install apache2 -y
          systemctl start apache2.service
          cd /var/www/html
          aws s3 cp s3://udacity-demo-1/udacity.zip .
          unzip -o udacity.zip
      SecurityGroups:
        - !Ref ServerSecGroup
    DependsOn: ServerSecGroup

  #Create a Target group -
  WebAppTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckIntervalSeconds: 35
      HealthCheckPath: /
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 30
      HealthyThresholdCount: 2
      Port: 80
      Protocol: HTTP
      UnhealthyThresholdCount: 5
      VpcId: 
        Fn::ImportValue:
          !Sub "${NetworkStack}-VPCID"

  WebAppLB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Subnets:
        - Fn::ImportValue:
            !Sub "${NetworkStack}-PUB1"
        - Fn::ImportValue:
            !Sub "${NetworkStack}-PUB2"
      SecurityGroups:
        - !Ref ServerSecGroup

  WebAppLBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    DependsOn:
      - WebAppLB
    Properties:
      DefaultActions:
        - TargetGroupArn: !Ref WebAppTargetGroup
          Type: 'forward'
      LoadBalancerArn: !Ref WebAppLB
      Port: 80
      Protocol: HTTP

  #Finally create an auto scaling group to launch your EC2 instances -
  WebAppAutoScale:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AutoScalingGroupName: !Sub ${NetworkStack}-AutoScale
      AvailabilityZones:
        - !Select [0, !GetAZs '']
        - !Select [1, !GetAZs '']
      VPCZoneIdentifier:
        - Fn::ImportValue:
            !Sub "${NetworkStack}-PRI1" #Change it to private
        - Fn::ImportValue:
            !Sub "${NetworkStack}-PRI2" #Change it to private
      LaunchConfigurationName:
        !Ref ServerLaunchConfig
      TargetGroupARNs:
        - !Ref WebAppTargetGroup
      MinSize: !Ref AutoScaleMinSize 
      MaxSize: !Ref AutoScaleMaxSize
      DesiredCapacity: !Ref AutoScaleDesiredSize
      HealthCheckGracePeriod: 180

Outputs:
  LoadBalancer:
    Description: Public URL of Load Balancer
    Value: 
      Fn::Join:
        - ""
        - - "http://"
          - Fn::GetAtt: WebAppLB.DNSName
    Export:
      Name: !Sub ${NetworkStack}-LB
